---
- hosts: 172.31.30.31
  become: yes
  tasks:
  - name: i want to execute direct linux
    command: hostname -f
    register: myresult

  - name: i want to display my first result
    debug:
      msg: "{{myresult}}" 