---
- hosts: 172.31.30.31
  become: yes
  tasks:
  - include_tasks: mfile.yml
  
  - name: copy file into node side
    copy:
      src: mytestfile
      dest: /home/ubuntu/mytestfile
    
  - name: i want to install webserver on ansible node
    apt:
      - name: apache2
        state: present

  - name: i want to copy index file into ansible node 
    template:
      src: mydynamicfile.j2
      dest: /var/www/html/index.html
    notify: restartwebserver
  
  - name: i want to download internet files
    get_url:
      url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
      dest: /home/ubuntu/apache-tomcat-10.0.20.tar.gz
      force_basic_auth: yes
    
  handlers:
  - name: restartwebserver
    service: 
      name: apache2
      state: restarted